### ISSUE TITLE
Mapleader must typed as <Leader>, not <leader>

### ISSUE THREAD

**Issue by hobo-mts** [mhinz/vim-galore#119]
and `<LocalLeader>`, not `<localleader>`. Capital `L`. IMHO.

**Comment by mhinz** [comment]
Sorry, but that would be inconsistent with all the other occurrences of lowercase key notations (which I prefer).

I understand that it would look slightly better in this case, but from all the key notations used in the text it would be the only one denoting two words.

So, instead of becoming inconsistent or changing _all_ key notations, I won't change it.

Thanks for bringing this up anyway!

**Comment by hobo-mts** [comment]
Want you or NOT want. But it is NOT works. IMHO. It's a Vim that grounds from UNIX where case is matter.

**Comment by mhinz** [comment]
What are you talking about? Vim doesn't care about the case within the key notations. Everything I wrote in this document is tested.

**Comment by hobo-mts** [comment]
Sorry. But... May be by Moon phase... 6 hours on other machine it were not work. I don't understand why. Sorry.
