### ISSUE TITLE
Invalid command :echo color_name?

### ISSUE THREAD

**Issue by hobo-mts** [mhinz/vim-galore#128]
Here:

```
The same, but only for the "lucius" colorscheme (check `:echo
color_name` which should be set by all valid colorschemes):
```

In my Vim 7.4 with default colorscheme, command `:echo color_name` prints 

```
E121: Undefined variable: color_name
E15: Invalid expression: color_name
```

_default.vim_ contains line `let colors_name = "default"`

**Comment by mhinz** [comment]
Okay, I changed the whole section to make it a bit clearer.

The default colorscheme is hardcoded in C and does not set `colors_name`. I should have used just `:colo`, which outputs `default` in that case.

Anyway, I removed the bit about `colors_name` since it's not really important. I also switched from "lucius" to one of the colorscheme shipped with Vim, "desert".

Thanks for bringing this up! ✨
