### ISSUE TITLE
Add something about how to create a plugin.

### ISSUE THREAD

**Issue by wsdjeg** [mhinz/vim-galore#74]
Hi @mhinz can you add something about how to create a plugin;

-  how and when vim source the script.

-  What is the order of loadin

-  how to write a autoload func

-  how to defind a command

-  how to defind a dict or list

thanks a lot

**Comment by mhinz** [comment]
Just defining commands and everything is stuff everyone can look up, so I most likely only reference the help files. So my approach will be much more practical. I'll simply show how to build a few small but useful plugins.

Since there is an issue for an VimL section already, I'll close this one. But feel free to further comment in here!

**Comment by wsdjeg** [comment]
yes, it is issue about VimL.
